# Generated by Django 3.1.5 on 2023-06-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(upload_to='projects/')),
                ('name', models.CharField(max_length=45)),
                ('description', models.TextField()),
                ('my_contributions', models.TextField()),
            ],
        ),
    ]
