# Generated by Django 3.1.5 on 2023-05-29 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20230529_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='test',
            field=models.TextField(blank=True),
        ),
    ]
